# Generated by Django 4.0.3 on 2022-05-17 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный?')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('bonuses', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название фильма')),
                ('slug', models.SlugField(verbose_name='URL')),
                ('country', models.CharField(max_length=50, verbose_name='Страна производства')),
                ('date_of_release', models.DateField(verbose_name='Старт проката')),
                ('description', models.TextField(blank=True, default='Описание будет позже', verbose_name='Описание')),
                ('image', models.ImageField(height_field='image_height', upload_to='images/', verbose_name='Изображение', width_field='image_width')),
                ('image_height', models.PositiveIntegerField(blank=True, default='525', editable=False, null=True)),
                ('image_width', models.PositiveIntegerField(blank=True, default='260', editable=False, null=True)),
                ('if_posted', models.BooleanField(default='True', verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_id', models.IntegerField(verbose_name='Номер зала')),
                ('type', models.CharField(choices=[('comfort', 'Комфорт'), ('standart', 'Стандарт')], default='standart', max_length=100, verbose_name='Тип зала')),
            ],
            options={
                'verbose_name': 'Зал',
                'verbose_name_plural': 'Залы',
            },
        ),
        migrations.CreateModel(
            name='Seans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='URL')),
                ('date_seans', models.DateField(verbose_name='Дата сеанса')),
                ('time_seans', models.TimeField(verbose_name='Время сеанса')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CinemaApp.film', verbose_name='Фильм')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CinemaApp.hall', verbose_name='Зал')),
            ],
            options={
                'verbose_name': 'Сеанс',
                'verbose_name_plural': 'Сеансы',
                'ordering': ['time_seans'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField(verbose_name='Ряд')),
                ('seat', models.IntegerField(verbose_name='Место')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, null=True, verbose_name='Цена')),
                ('available', models.BooleanField(default=True, verbose_name='Доступность')),
                ('reserved', models.BooleanField(default=False, verbose_name='Забронирован')),
                ('seans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CinemaApp.seans', verbose_name='Сеанс')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, verbose_name='Номер телефона')),
                ('email', models.CharField(max_length=100, verbose_name='Электронная почта')),
                ('created_at', models.DateField(auto_now=True, verbose_name='Дата заказа')),
                ('use_bonuses', models.BooleanField(default=False, verbose_name='Списать бонусы')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='CinemaApp.customer', verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.AddField(
            model_name='film',
            name='genre',
            field=models.ManyToManyField(related_name='film', to='CinemaApp.genre', verbose_name='Жанр'),
        ),
        migrations.AddField(
            model_name='customer',
            name='cutomer_orders',
            field=models.ManyToManyField(blank=True, related_name='related_customer', to='CinemaApp.order', verbose_name='Заказы покупателя'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='Количество билетов')),
                ('sum', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Цена')),
                ('in_order', models.BooleanField(default=False)),
                ('for_anonymous_user', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CinemaApp.customer', verbose_name='Покупатель')),
                ('tickets', models.ManyToManyField(blank=True, related_name='related_cart', to='CinemaApp.bron', verbose_name='Забронированные билеты')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
        migrations.AddField(
            model_name='bron',
            name='cart',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='CinemaApp.cart', verbose_name='Корзина'),
        ),
        migrations.AddField(
            model_name='bron',
            name='ticket',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='CinemaApp.ticket', verbose_name='Забронированный билет'),
        ),
        migrations.AddField(
            model_name='bron',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CinemaApp.customer', verbose_name='Покупатель'),
        ),
    ]
