# Generated by Django 4.0.3 on 2022-05-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='bonuses',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Бонусы'),
        ),
    ]
