# Generated by Django 4.0.3 on 2022-05-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaApp', '0002_alter_customer_bonuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='bought',
            field=models.BooleanField(default=True, verbose_name='Куплен'),
        ),
    ]
