# Generated by Django 4.0.3 on 2022-05-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaApp', '0003_ticket_bought'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='bought',
            field=models.BooleanField(default=False, verbose_name='Куплен'),
        ),
    ]
